/*2、每日竞猜国家队
http://58.20.27.5/MemberInterface/GetActiveInfoChild?activityId=*&type=0&userId=*&usertoken=*&fromsource=5
*/

var childACT = {
	"Message": null,
	"Result": 0,
	"Count": 0,
	"Data": {
		"children": [

		],
		"child": null,
		"children2": [{
				"children": [

				],
				"child": [

				],
				"children2": [

				],
				"items": [{
						"id": "37000002",
						"activityId": "40",
						"title": "乌拉洼",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:25:59",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:25:59",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					},
					{
						"id": "37000001",
						"activityId": "40",
						"title": "埃及",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:25:33",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:25:33",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					}
				],
				"dataitems": null,
				"menuList": null,
				"questionList": null,
				"userCount": 0,
				"id": "40",
				"groupId": "e765536fe8274d6ab2db05234732ee5e",
				"title": "埃及-乌拉洼",
				"showName": "06月15日_埃及-乌拉洼",
				"type": "2",
				"dataType": null,
				"description": "",
				"sort": "0",
				"status": "0",
				"payRatio": null,
				"parentId": "37",
				"sequences": "000026000001",
				"createTime": "2018-05-29 17:32:07",
				"isDelete": "0",
				"extend1": "",
				"extend2": "",
				"extend3": "",
				"extend4": "",
				"extend5": "",
				"images1": "",
				"images2": "",
				"images3": "",
				"images4": "",
				"usercount": "u1:1,u2:1,u3:1,u4:1,",
				"period": "0",
				"materialcount": "0",
				"images5": "",
				"images6": "",
				"images7": "",
				"images8": "",
				"images9": "",
				"images10": "",
				"images11": "",
				"images12": "",
				"images13": "",
				"onlinetime": null,
				"offlinetime": null
			},
			{
				"children": [

				],
				"child": [

				],
				"children2": [

				],
				"items": [{
						"id": "38000002",
						"activityId": "41",
						"title": "伊朗",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:28:34",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:28:34",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					},
					{
						"id": "38000001",
						"activityId": "41",
						"title": "莫咯哥",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:26:59",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:26:59",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					}
				],
				"dataitems": null,
				"menuList": null,
				"questionList": null,
				"userCount": 0,
				"id": "41",
				"groupId": "63f2779d89aa454585e735aaadf4476f",
				"title": "莫咯哥-伊朗",
				"showName": "06月15日_莫咯哥-伊朗",
				"type": "2",
				"dataType": null,
				"description": "",
				"sort": "0",
				"status": "0",
				"payRatio": null,
				"parentId": "37",
				"sequences": "000025",
				"createTime": "2018-05-29 17:32:39",
				"isDelete": "0",
				"extend1": "",
				"extend2": "",
				"extend3": "",
				"extend4": "",
				"extend5": "",
				"images1": "",
				"images2": "",
				"images3": "",
				"images4": "",
				"usercount": "u1:1,u2:1,u3:1,u4:1,",
				"period": "0",
				"materialcount": "0",
				"images5": "",
				"images6": "",
				"images7": "",
				"images8": "",
				"images9": "",
				"images10": "",
				"images11": "",
				"images12": "",
				"images13": "",
				"onlinetime": null,
				"offlinetime": null
			},
			{
				"children": [

				],
				"child": [

				],
				"children2": [

				],
				"items": [{
						"id": "38000002",
						"activityId": "41",
						"title": "伊朗",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:28:34",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:28:34",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					},
					{
						"id": "38000001",
						"activityId": "41",
						"title": "莫咯哥",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:26:59",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:26:59",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					}
				],
				"dataitems": null,
				"menuList": null,
				"questionList": null,
				"userCount": 0,
				"id": "41",
				"groupId": "63f2779d89aa454585e735aaadf4476f",
				"title": "莫咯哥-伊朗",
				"showName": "06月15日_莫咯哥-伊朗",
				"type": "2",
				"dataType": null,
				"description": "",
				"sort": "0",
				"status": "0",
				"payRatio": null,
				"parentId": "37",
				"sequences": "000025",
				"createTime": "2018-05-29 17:32:39",
				"isDelete": "0",
				"extend1": "",
				"extend2": "",
				"extend3": "",
				"extend4": "",
				"extend5": "",
				"images1": "",
				"images2": "",
				"images3": "",
				"images4": "",
				"usercount": "u1:1,u2:1,u3:1,u4:1,",
				"period": "0",
				"materialcount": "0",
				"images5": "",
				"images6": "",
				"images7": "",
				"images8": "",
				"images9": "",
				"images10": "",
				"images11": "",
				"images12": "",
				"images13": "",
				"onlinetime": null,
				"offlinetime": null
			},
			{
				"children": [

				],
				"child": [

				],
				"children2": [

				],
				"items": [{
						"id": "38000002",
						"activityId": "41",
						"title": "伊朗",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:28:34",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:28:34",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					},
					{
						"id": "38000001",
						"activityId": "41",
						"title": "莫咯哥",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:26:59",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:26:59",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					}
				],
				"dataitems": null,
				"menuList": null,
				"questionList": null,
				"userCount": 0,
				"id": "41",
				"groupId": "63f2779d89aa454585e735aaadf4476f",
				"title": "莫咯哥-伊朗",
				"showName": "06月15日_莫咯哥-伊朗",
				"type": "2",
				"dataType": null,
				"description": "",
				"sort": "0",
				"status": "0",
				"payRatio": null,
				"parentId": "37",
				"sequences": "000025",
				"createTime": "2018-05-29 17:32:39",
				"isDelete": "0",
				"extend1": "",
				"extend2": "",
				"extend3": "",
				"extend4": "",
				"extend5": "",
				"images1": "",
				"images2": "",
				"images3": "",
				"images4": "",
				"usercount": "u1:1,u2:1,u3:1,u4:1,",
				"period": "0",
				"materialcount": "0",
				"images5": "",
				"images6": "",
				"images7": "",
				"images8": "",
				"images9": "",
				"images10": "",
				"images11": "",
				"images12": "",
				"images13": "",
				"onlinetime": null,
				"offlinetime": null
			},
			{
				"children": [

				],
				"child": [

				],
				"children2": [

				],
				"items": [{
						"id": "38000002",
						"activityId": "41",
						"title": "伊朗",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:28:34",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:28:34",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					},
					{
						"id": "38000001",
						"activityId": "41",
						"title": "莫咯哥",
						"type": "0",
						"description": "",
						"popularity": "0",
						"votenums": "0",
						"losenums": "0",
						"prizeTotal": "0",
						"winningTotal": "0",
						"isCardPrizes": "0",
						"cardType": null,
						"sort": "0",
						"status": "0",
						"startTime": "2018-05-29 17:26:59",
						"endTime": null,
						"url": "",
						"areaId": "",
						"dataId1": null,
						"dataId2": null,
						"dataId3": null,
						"dataId4": null,
						"images1": "",
						"images2": "",
						"images3": "",
						"images4": "",
						"video1": "",
						"video2": "",
						"video3": "",
						"video4": "",
						"video5": "",
						"video6": "",
						"video7": "",
						"video8": "",
						"createTime": "2018-05-29 17:26:59",
						"isDelete": "0",
						"extend1": "",
						"extend2": "",
						"extend3": "",
						"extend4": "",
						"extend5": "",
						"extend6": "",
						"userLotteryCount": 0,
						"userCurrentLotteryCount": 0,
						"period": "1",
						"usercond": "u1:0,u2:,u3:0,u4:,",
						"probability": "2",
						"random": null,
						"isrepeat": "1",
						"prizetype": "10",
						"meziname": "",
						"diamondstartTime": null,
						"diamondendTime": null
					}
				],
				"dataitems": null,
				"menuList": null,
				"questionList": null,
				"userCount": 0,
				"id": "41",
				"groupId": "63f2779d89aa454585e735aaadf4476f",
				"title": "莫咯哥-伊朗",
				"showName": "06月15日_莫咯哥-伊朗",
				"type": "2",
				"dataType": null,
				"description": "",
				"sort": "0",
				"status": "0",
				"payRatio": null,
				"parentId": "37",
				"sequences": "000025",
				"createTime": "2018-05-29 17:32:39",
				"isDelete": "0",
				"extend1": "",
				"extend2": "",
				"extend3": "",
				"extend4": "",
				"extend5": "",
				"images1": "",
				"images2": "",
				"images3": "",
				"images4": "",
				"usercount": "u1:1,u2:1,u3:1,u4:1,",
				"period": "0",
				"materialcount": "0",
				"images5": "",
				"images6": "",
				"images7": "",
				"images8": "",
				"images9": "",
				"images10": "",
				"images11": "",
				"images12": "",
				"images13": "",
				"onlinetime": null,
				"offlinetime": null
			}
		],
		"items": [

		],
		"dataitems": null,
		"menuList": null,
		"questionList": null,
		"userCount": 0,
		"id": "37",
		"groupId": "be13a483eb6545c29a23f0456f448d5b",
		"title": "06月15日",
		"showName": "世界杯竞猜_06月15日",
		"type": "1",
		"dataType": null,
		"description": "",
		"sort": "0",
		"status": "0",
		"payRatio": null,
		"parentId": "35",
		"sequences": "000026",
		"createTime": "2018-05-29 17:23:47",
		"isDelete": "0",
		"extend1": "",
		"extend2": "",
		"extend3": "",
		"extend4": "",
		"extend5": "",
		"images1": "",
		"images2": "",
		"images3": "",
		"images4": "",
		"usercount": "u1:0,u2:0,u3:0,u4:0,",
		"period": "0",
		"materialcount": "0",
		"images5": "",
		"images6": "",
		"images7": "",
		"images8": "",
		"images9": "",
		"images10": "",
		"images11": "",
		"images12": "",
		"images13": "",
		"onlinetime": null,
		"offlinetime": null
	},
	"id": null,
	"SmsId": null,
	"Flag": null,
	"Count2": 0,
	"LotteryCount": 0,
	"Allcount": 0,
	"total": 0,
	"time": null
}