"<canvasid=\"my-canvas\"></canvas>"+
"<divid=\"clock\">"+
"<divclass=\"time-containerhours\">"+
"<divclass=\"digit\">"+
"<divclass=\"fade\">&nbsp;</div>"+
"<spanclass=\"numtop\"id=\"hour-tens-top\"></span>"+
"<spanclass=\"numbottom\"id=\"hour-tens-bottom\">"+
"<divclass=\"bottom-container\"></div></span>"+
"<divclass=\"swapper\">"+
"<divid=\"top-hour-tens-anim\"class=\"num-animtop-anim\"style=\"display:none;\">"+
"<divclass=\"top-half-num\"></div>"+
"</div>"+
"<divid=\"bottom-hour-tens-anim\"class=\"num-animbottom-anim\"style=\"display:none;\">"+
"<divclass=\"bottom-half-num\">"+
"<divclass=\"dropper\"></div></div>"+
"</div>"+
"</div>"+
"<divclass=\"ringring-left\"></div>"+
"<divclass=\"ringring-right\"></div>"+
"</div>"+
"<divclass=\"digit\">"+
"<divclass=\"fade\">&nbsp;</div>"+
"<spanclass=\"numtop\"id=\"hour-ones-top\"></span>"+
"<spanclass=\"numbottom\"id=\"hour-ones-bottom\">"+
"<divclass=\"bottom-container\"></div></span>"+
"<divclass=\"swapper\">"+
"<divid=\"top-hour-ones-anim\"class=\"num-animtop-anim\"style=\"display:none;\">"+
"<divclass=\"top-half-num\"></div>"+
"</div>"+
"<divid=\"bottom-hour-ones-anim\"class=\"num-animbottom-anim\"style=\"display:none;\">"+
"<divclass=\"bottom-half-num\">"+
"<divclass=\"dropper\"></div></div>"+
"</div>"+
"</div>"+
"<divclass=\"ringring-left\"></div>"+
"<divclass=\"ringring-right\"></div>"+
"</div>"+
"</div>"+
"<divclass=\"time-containerminutes\">"+
"<divclass=\"digit\">"+
"<divclass=\"fade\">&nbsp;</div>"+
"<spanclass=\"numtop\"id=\"minute-tens-top\"></span>"+
"<spanclass=\"numbottom\"id=\"minute-tens-bottom\">"+
"<divclass=\"bottom-container\"></div></span>"+
"<divclass=\"swapper\">"+
"<divid=\"top-minute-tens-anim\"class=\"num-animtop-anim\"style=\"display:none;\">"+
"<divclass=\"top-half-num\"></div>"+
"</div>"+
"<divid=\"bottom-minute-tens-anim\"class=\"num-animbottom-anim\"style=\"display:none;\">"+
"<divclass=\"bottom-half-num\">"+
"<divclass=\"dropper\"></div></div>"+
"</div>"+
"</div>"+
"<divclass=\"ringring-left\"></div>"+
"<divclass=\"ringring-right\"></div>"+
"</div>"+
"<divclass=\"digit\">"+
"<divclass=\"fade\">&nbsp;</div>"+
"<spanclass=\"numtop\"id=\"minute-ones-top\"></span>"+
"<spanclass=\"numbottom\"id=\"minute-ones-bottom\">"+
"<divclass=\"bottom-container\"></div></span>"+
"<divclass=\"swapper\">"+
"<divid=\"top-minute-ones-anim\"class=\"num-animtop-anim\"style=\"display:none;\">"+
"<divclass=\"top-half-num\"></div>"+
"</div>"+
"<divid=\"bottom-minute-ones-anim\"class=\"num-animbottom-anim\"style=\"display:none;\">"+
"<divclass=\"bottom-half-num\">"+
"<divclass=\"dropper\"></div></div>"+
"</div>"+
"</div>"+
"<divclass=\"ringring-left\"></div>"+
"<divclass=\"ringring-right\"></div>"+
"</div>"+
"</div>"+
"<divclass=\"time-containerseconds\">"+
"<divclass=\"digit\">"+
"<divclass=\"fade\">&nbsp;</div>"+
"<spanclass=\"numtop\"id=\"second-tens-top\"></span>"+
"<spanclass=\"numbottom\"id=\"second-tens-bottom\">"+
"<divclass=\"bottom-container\"></div></span>"+
"<divclass=\"swapper\">"+
"<divid=\"top-second-tens-anim\"class=\"num-animtop-anim\"style=\"display:none;\">"+
"<divclass=\"top-half-num\"></div>"+
"</div>"+
"<divid=\"bottom-second-tens-anim\"class=\"num-animbottom-anim\"style=\"display:none;\">"+
"<divclass=\"bottom-half-num\">"+
"<divclass=\"dropper\"></div></div>"+
"</div>"+
"</div>"+
"<divclass=\"ringring-left\"></div>"+
"<divclass=\"ringring-right\"></div>"+
"</div>"+
"<divclass=\"digit\">"+
"<divclass=\"fade\">&nbsp;</div>"+
"<spanclass=\"numtop\"id=\"second-ones-top\"></span>"+
"<spanclass=\"numbottom\"id=\"second-ones-bottom\">"+
"<divclass=\"bottom-container\"></div></span>"+
"<divclass=\"swapper\">"+
"<divid=\"top-second-ones-anim\"class=\"num-animtop-anim\"style=\"display:none;\">"+
"<divclass=\"top-half-num\"></div>"+
"</div>"+
"<divid=\"bottom-second-ones-anim\"class=\"num-animbottom-anim\"style=\"display:none;\">"+
"<divclass=\"bottom-half-num\">"+
"<divclass=\"dropper\"></div></div>"+
"</div>"+
"</div>"+
"<divclass=\"ringring-left\"></div>"+
"<divclass=\"ringring-right\"></div>"+
"</div>"+
"</div>"+
"</div>"